name: deploy

on:
  push:
  workflow_dispatch:
  schedule:
    # Runs everyday at 8:00 AM
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"

      - name: Build Web
        run: hugo

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          PERSONAL_TOKEN: ${{ secrets.HUGO_BLOG_PRIVATE }}
          EXTERNAL_REPOSITORY: w-howey/w-howey.github.io
          PUBLISH_BRANCH: master
          cname: github.com
          PUBLISH_DIR: "./public"
          commit_message: ${{ github.event.head_commit.message }}
          allow_empty_commit: true
